### ISSUE TITLE
bug report: need to check if the parameters are valid

### ISSUE THREAD

**Issue by WALL-E** [yuuki0xff/conoha-cli#2]
>[root@localhost ~]# conoha-cli compute add-key -n 192.168.1.1 -f ~/.ssh/id_rsa.pub
```
Traceback (most recent call last):
  File "/usr/local/bin/conoha-cli", line 11, in <module>
    load_entry_point('conoha-cli==0.1.1', 'console_scripts', 'conoha-cli')()
  File "/usr/local/lib/python3.6/site-packages/conoha/cli.py", line 117, in main
    token = Token(conf)
  File "/usr/local/lib/python3.6/site-packages/conoha/api.py", line 102, in __init__
    res = self._POST(path, data)
  File "/usr/local/lib/python3.6/site-packages/conoha/api.py", line 81, in _POST
    return self._GET(path, data, *args, method='POST', **nargs)
  File "/usr/local/lib/python3.6/site-packages/conoha/api.py", line 63, in _GET
    with urlopen(req) as res:
  File "/usr/local/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
```

**Comment by WALL-E** [comment]
# ConoHa Control Panel
![conoha-add-key-en](https://user-images.githubusercontent.com/736927/30004287-03e42bdc-90ff-11e7-83b7-006ed097a44c.png)

@yuuki0xff Could you take some time to fix it?

**Comment by yuuki0xff** [comment]
Thank you for issues report.
To tell the truth, this product has not enough input validations :-(
I think I want to fix this problem until tomorrow.
