### ISSUE TITLE
HTTP Error 401: Unauthorized

### ISSUE THREAD

**Issue by CRC32EX** [yuuki0xff/conoha-cli#4]
# Steps to reproduce this issue
1. Install conoha-cli
```
$ pip3 install conoha-cli
```

2. Set environment variables
https://user-images.githubusercontent.com/25629617/71791589-e4241480-3078-11ea-8f22-21b8e9736c53.png
```
$ ~/.bashrc
# 1 テナントID
export CONOHA_API_USER='xxxxx'
# 2 ユーザー名
export CONOHA_API_PASSWD='xxxxx'
# 3 パスワード
export CONOHA_API_TENANT='xxxxx'

$ source ~/.bashrc
```

3. Run command
```
$ conoha-cli compute add-vm -w
```

# Error detail
```
$ conoha-cli compute add-vm -w
Traceback (most recent call last):
  File "/home/user01/.pyenv/versions/3.7.3/bin/conoha-cli", line 11, in <module>
    load_entry_point('conoha-cli==0.2.0', 'console_scripts', 'conoha-cli')()
  File "/home/user01/.pyenv/versions/3.7.3/lib/python3.7/site-packages/conoha/cli.py", line 126, in main
    token = Token(conf)
  File "/home/user01/.pyenv/versions/3.7.3/lib/python3.7/site-packages/conoha/api.py", line 102, in __init__
    res = self._POST(path, data)
  File "/home/user01/.pyenv/versions/3.7.3/lib/python3.7/site-packages/conoha/api.py", line 81, in _POST
    return self._GET(path, data, *args, method='POST', **nargs)
  File "/home/user01/.pyenv/versions/3.7.3/lib/python3.7/site-packages/conoha/api.py", line 63, in _GET
    with urlopen(req) as res:
  File "/home/user01/.pyenv/versions/3.7.3/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/user01/.pyenv/versions/3.7.3/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/user01/.pyenv/versions/3.7.3/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/user01/.pyenv/versions/3.7.3/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/user01/.pyenv/versions/3.7.3/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/user01/.pyenv/versions/3.7.3/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized
```

# My Environment
|#|#|
|:--|:--|
|OS|WSL (Ubuntu16.04) (Windows 10 64bit Pro)|
|Python|3.7.3|

**Comment by CRC32EX** [comment]
No response over 1 month.
This project is already dead.

I recommend to use `giginc/conoha` instead of this project.
https://github.com/giginc/conoha

**Comment by yuuki0xff** [comment]
Sorry for the very late reply. I am closing this issue because the above MR will fix it.

This project is no longer maintained. I would describe this project state and alternative project to README and repository description.
